runtime: nodejs16

env_variables:
  DB_USER: your-db-user
  CLOUD_SQL_CONNECTION_NAME: my-project-id:us-central1:my-instance-id
  DB_NAME: your-db-name
  DB_PASSWORD: your-db-password
  DB_PORT: 5432
  ML_MODEL_URL: https://your-cloud-run-url.a.run.app/predict

handlers:
  - url: /static
    static_dir: public/

  - url: /.* 
    script: auto
